version: 0.0.{build}
image: Visual Studio 2017
environment:
  my_variable:
    secure: Qpq/4cyuTUzmt/r4HsQxioG6WXrZSK3mzVq5iUJC2RI=
build_script:
- cmd: PowerShell.exe -NoProfile -ExecutionPolicy Bypass -Command "& '.\build.ps1' --target Clean Pack CreateSetup PublishToAppveyor ChangeVersionNumber --Configuration Release"
test: off